name: ${project.name}
main: com.github.brun0xp.orateplugin.Main
version: ${project.version}
description: ${project.description}
author: Brun0XP
depend: [WorldGuard]

commands:
  orar:
    description: Orate command